name: CI → GitOps - {{ github.base_ref }}
on:
#   push:
#     branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gitops:
    uses: shivam779823/cicd-resusable-workflows/.github/workflows/ci-workflow-v1.yaml@dev
    with:
      image_name: argocd-cicd-image
      deployment_repo: shivam779823/ArgoCD-CICD-deployment-repo
      deployment_branch: main
      manifest_path: k8s/
      run_tests: false

    secrets:
      GITOPS_PAT: ${{ secrets.GITOPS_PAT }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

